
ALL: lib

SOURCEH  = ../../include/permon/private/svmimpl.h ../../include/permonsvm.h
DIRS     = interface impls 
LOCDIR   = src/svm/
MANSEC   = SVM

include ${PERMON_SVM_DIR}/lib/permonsvm/conf/permonsvm_variables
include ${PERMON_SVM_DIR}/lib/permonsvm/conf/permonsvm_rules
