
ALL: lib

LIBBASE  = libpermon
DIRS     = binary
LOCDIR   = src/svm/impls/
MANSEX   = SVM

include ${PERMON_SVM_DIR}/lib/permonsvm/conf/permonsvm_variables
include ${PERMON_SVM_DIR}/lib/permonsvm/conf/permonsvm_rules
