
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = binary.c
SOURCEF  =
SOURCEH  =
OBJSC    = ${SOURCEC:.c=.o}
OBJSF    =
LIBBASE  = libpermon
MANSEC   = SVM
LOCDIR   = src/svm/impls/binary/

include ${PERMON_SVM_DIR}/lib/permonsvm/conf/permonsvm_variables
include ${PERMON_SVM_DIR}/lib/permonsvm/conf/permonsvm_rules
