
ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = dummy.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = ${SOURCEC:.c=.o} 
LIBBASE  = libPermonDummy
DIRS     =
MANSEC   = Dummy
LOCDIR   = src/dummy/interface/

include ${PERMON_DUMMY_DIR}/lib/PermonDummy/conf/permon_dummy_variables
include ${PERMON_DUMMY_DIR}/lib/PermonDummy/conf/permon_dummy_rules

