ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = io.c report.c matutils.c
SOURCEF  =
SOURCEH  = io.h report.h
OBJSC    = ${SOURCEC:.c=.o}
LIBBASE  = libpermon
DIRS     =
MANSEC   = SVM
LOCDIR   = src/svm/utils/

include ${PERMON_SVM_DIR}/lib/permonsvm/conf/permonsvm_variables
include ${PERMON_SVM_DIR}/lib/permonsvm/conf/permonsvm_rules
