ALL: exbinfile

CFLAGS      = -I.
FFLAGS      =
CPPFLAGS    =
FPPFLAGS    =
TUTORIALS   = exbinfile.c
EXAMPLESC   = exbinfile.c
EXAMPLECH   =
EXAMPLESF   =
EXAMPLESFH  =
LOCDIR      = src/examples
MANSEC      =
DOCS        =
DIRS        =
CLEANFILES  = exbinfile

include ${PERMON_SVM_DIR}/lib/permonsvm/conf/permonsvm_base
include ${PERMON_SVM_DIR}/lib/permonsvm/conf/permonsvm_test

