ALL: lib

CFLAGS   =
FFLAGS   =
SOURCEC  = dlregissvm.c svm.c
SOURCEF  = 
SOURCEH  = 
OBJSC    = ${SOURCEC:.c=.o}
LIBBASE  = libpermon
DIRS     =
MANSEC   = SVM
LOCDIR   = src/svm/interface/

include ${PERMON_SVM_DIR}/lib/permonsvm/conf/permonsvm_variables
include ${PERMON_SVM_DIR}/lib/permonsvm/conf/permonsvm_rules
