
ALL: lib

SOURCEH  = ../../include/private/dummyimpl.h ../../include/permondummy.h
DIRS     = interface impls
LOCDIR   = src/dummy/
MANSEC   = Dummy

include ${PERMON_DUMMY_DIR}/lib/PermonDummy/conf/permon_dummy_variables
include ${PERMON_DUMMY_DIR}/lib/PermonDummy/conf/permon_dummy_rules

