
ALL: lib

LIBBASE  = libPermonDummy
DIRS     = 
LOCDIR   = src/dummy/impls/
MANSEC   = Dummy

include ${PERMON_DUMMY_DIR}/lib/PermonDummy/conf/permon_dummy_variables
include ${PERMON_DUMMY_DIR}/lib/PermonDummy/conf/permon_dummy_rules

